### YamlMime:UniversalReference
items:
  - uid: '@azure/servicefabric.TestErrorChaosEvent'
    name: TestErrorChaosEvent
    fullName: TestErrorChaosEvent
    children:
      - '@azure/servicefabric.TestErrorChaosEvent.kind'
      - '@azure/servicefabric.TestErrorChaosEvent.reason'
      - '@azure/servicefabric.TestErrorChaosEvent.timeStampUtc'
    langs:
      - typeScript
    type: interface
    summary: |-
      <span data-ttu-id="cdbf5-101">Chaos 엔진에서 예기치 않은 이벤트가 발생할 때 생성 되는 비정상 상황 이벤트를 설명 합니다.</span><span class="sxs-lookup"><span data-stu-id="cdbf5-101">Describes a Chaos event that gets generated when an unexpected event occurs in the Chaos engine.</span></span>
      <span data-ttu-id="cdbf5-102">예를 들어, 클러스터 스냅숏 엔터티의 오류가 발생 하는 동안 일관 되지 않은 것으로 인해 Chaos 찾을 엔터티가 이미 오류가 발생 했습니다-예기치 않은 이벤트는 것입니다.</span><span class="sxs-lookup"><span data-stu-id="cdbf5-102">For example, due to the cluster snapshot being inconsistent, while faulting an entity, Chaos found that the entity was already faulted -- which would be an unexpected event.</span></span>
    package: '@azure/servicefabric'
  - uid: '@azure/servicefabric.TestErrorChaosEvent.kind'
    name: kind
    fullName: kind
    children: []
    langs:
      - typeScript
    type: property
    summary: <span data-ttu-id="cdbf5-103">다형 판별자</span><span class="sxs-lookup"><span data-stu-id="cdbf5-103">Polymorphic Discriminator</span></span>
    syntax:
      content: 'kind: "TestError"'
      return:
        type:
          - '"TestError"'
    package: '@azure/servicefabric'
  - uid: '@azure/servicefabric.TestErrorChaosEvent.reason'
    name: reason
    fullName: reason
    children: []
    langs:
      - typeScript
    type: property
    summary: '<span data-ttu-id="cdbf5-104">TestErrorChaosEvent 생성 된 이유를 설명 합니다.</span><span class="sxs-lookup"><span data-stu-id="cdbf5-104">Describes why TestErrorChaosEvent was generated.</span></span> <span data-ttu-id="cdbf5-105">예를 들어, 비정상 상황 오류를 파티션 하려고 했지만는 파티션을 내결함성을 갖추고, 더 이상 다음을 TestErrorEvent는 이유는 파티션 하지 않다는 내결함성이로 생성 찾은 표시 합니다.</span><span class="sxs-lookup"><span data-stu-id="cdbf5-105">For example, Chaos tries to fault a partition but finds that the partition is no longer fault tolerant, then a TestErrorEvent gets generated with the reason stating that the partition is not fault tolerant.</span></span>'
    optional: true
    syntax:
      content: 'reason?: undefined | string'
      return:
        type:
          - undefined | string
    package: '@azure/servicefabric'
  - uid: '@azure/servicefabric.TestErrorChaosEvent.timeStampUtc'
    name: timeStampUtc
    fullName: timeStampUtc
    children: []
    langs:
      - typeScript
    type: property
    summary: <span data-ttu-id="cdbf5-106">UTC 타임 스탬프가 비정상 상황 이벤트가 생성 된 경우.</span><span class="sxs-lookup"><span data-stu-id="cdbf5-106">The UTC timestamp when this Chaos event was generated.</span></span>
    syntax:
      content: 'timeStampUtc: Date'
      return:
        type:
          - Date
    package: '@azure/servicefabric'